"""Verify a tested renderer DLL and its separate notices/build record."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from gk3hd.renderer.distribution import ASSET_NAME, MAX_DLL_BYTES, REPOSITORY
from gk3hd.renderer.distribution import validate_dll as _verify_dll
from gk3hd.system.files import sha256_file

_TOOLS = Path(__file__).resolve().parent
_TAG = re.compile(r"v[0-9]+(?:\.[0-9]+){1,2}")
_ASSET_URL = re.compile(
    r"https://github\.com/lsorber/gk3hd/releases/download/"
    r"(v[0-9]+(?:\.[0-9]+){1,2})/(d7vk-[0-9.]+-gk3hd\.[0-9]+\.dll)"
)
_LICENSES = (
    "D7VK.txt",
    "dxbc-spirv.txt",
    "libdisplay-info.txt",
    "SPIRV-Headers.txt",
    "dxbc-SPIRV-Headers.txt",
    "Vulkan-Headers.txt",
    "Vulkan-MIT.txt",
    "Vulkan-Apache-2.0.txt",
    "OpenVR.txt",
)


@dataclass(frozen=True, slots=True)
class RendererAsset:
    """Verified DLL plus release-only companions; no archive is installed."""

    path: Path
    version: str
    dll_sha256: str
    dll_size: int
    companions: tuple[tuple[Path, str], ...] = ()

    @property
    def uploads(self) -> tuple[Path, ...]:
        """Release assets, including notices and provenance alongside the DLL."""
        return (self.path, *(path for path, _ in self.companions))

    def verify_unchanged(self) -> None:
        """Reject substitutions between preflight and release publication."""
        if (
            self.path.stat().st_size != self.dll_size
            or sha256_file(self.path) != self.dll_sha256
            or any(sha256_file(path) != digest for path, digest in self.companions)
        ):
            msg = "renderer files changed after verification; inspect the build again"
            raise ValueError(msg)

    def lock(self, tag: str) -> dict[str, str]:
        """Record the package's tested renderer baseline before uploading."""
        if _TAG.fullmatch(tag) is None:
            msg = "invalid gk3hd release tag"
            raise ValueError(msg)
        return {
            "asset_url": f"https://github.com/{REPOSITORY}/releases/download/{tag}/{self.path.name}",
            "dll_sha256": self.dll_sha256,
            "dll_size": str(self.dll_size),
            "license": "Zlib",
            "repository": REPOSITORY,
            "version": self.version,
        }


def inspect_dll(path: Path) -> RendererAsset:
    """Validate the recipe's DLL, native-test results, source hashes and notices.

    The companions are generated by `d7vk build` and uploaded separately.
    This gate never executes a supplied binary and cannot replace gameplay review.
    """
    pin = json.loads((_TOOLS / "upstream.json").read_text(encoding="utf-8"))
    match = ASSET_NAME.fullmatch(path.name)
    if match is None or match[1] != pin["version"] or not 0 < path.stat().st_size <= MAX_DLL_BYTES:
        msg = f"expected the build recipe's d7vk-{pin['version']}.dll (at most 32 MiB)"
        raise ValueError(msg)
    dll = path.read_bytes()
    _verify_dll(dll)
    digest = hashlib.sha256(dll).hexdigest()
    provenance = path.with_suffix(".json")
    notices = path.with_suffix(".txt")
    build = json.loads(provenance.read_text(encoding="utf-8"))
    expected = {
        "version": pin["version"],
        "upstream_commit": pin["commit"],
        **{key: pin[key] for key in ("msvc", "windows_sdk", "meson", "ninja")},
        "source_path_mapping": "gk3hd-build",
        "patch_sha256": sha256_file(_TOOLS / "renderer.patch"),
        "dll_sha256": digest,
        "surface_tests": "passed",
        "helper_tests": "passed",
        "notices_sha256": sha256_file(notices),
    }
    if not isinstance(build, dict) or any(
        build.get(key) != value for key, value in expected.items()
    ):
        msg = "renderer provenance differs from the reviewed recipe, test results or DLL"
        raise ValueError(msg)
    text = notices.read_text(encoding="utf-8")
    if not all(f"=== {name} ===" in text for name in _LICENSES):
        msg = "renderer notices are missing required third-party entries"
        raise ValueError(msg)
    return RendererAsset(
        path,
        match[1],
        digest,
        len(dll),
        ((provenance, sha256_file(provenance)), (notices, sha256_file(notices))),
    )


def release_target(lock: object) -> tuple[str, str, str]:
    """Validate the baseline's immutable gk3hd DLL URL and SHA-256."""
    if not isinstance(lock, dict) or not isinstance(lock.get("asset_url"), str):
        msg = "invalid renderer lock; prepare a tested build with --renderer"
        raise TypeError(msg)
    match = _ASSET_URL.fullmatch(lock["asset_url"])
    digest = lock.get("dll_sha256")
    if (
        match is None
        or not isinstance(digest, str)
        or re.fullmatch(r"[0-9a-f]{64}", digest) is None
    ):
        msg = "renderer lock must pin an immutable DLL release and SHA-256"
        raise ValueError(msg)
    return REPOSITORY, match[1], match[2]


def validate_release_assets(lock: object, release: object) -> None:
    """Check the published DLL identity and presence of its separate companions."""
    _, tag, filename = release_target(lock)
    if not isinstance(lock, dict) or not isinstance(release, dict):
        msg = "invalid renderer release inventory"
        raise TypeError(msg)
    if release.get("tag_name") != tag or not isinstance(release.get("assets"), list):
        msg = "renderer release inventory does not match the pinned tag"
        raise ValueError(msg)
    for name in (filename, filename[:-4] + ".json", filename[:-4] + ".txt"):
        matches = [
            asset
            for asset in release["assets"]
            if isinstance(asset, dict) and asset.get("name") == name
        ]
        if len(matches) != 1:
            msg = f"renderer release is missing unique asset {name}"
            raise ValueError(msg)
        asset = matches[0]
        digest, size = asset.get("digest"), asset.get("size")
        if (
            asset.get("state") != "uploaded"
            or not isinstance(digest, str)
            or re.fullmatch(r"sha256:[0-9a-f]{64}", digest) is None
            or type(size) is not int
            or size <= 0
            or (
                name == filename
                and (digest != "sha256:" + lock["dll_sha256"] or str(size) != lock.get("dll_size"))
            )
        ):
            msg = f"renderer asset {name} is incomplete or differs from its pinned size/SHA-256"
            raise ValueError(msg)
